# import_rust_crate(MANIFEST_PATH path/to/Cargo.toml CRATE_NAME name [PANIC_UNWIND])
#
# Builds a Rust static library crate using cargo and creates an IMPORTED target.
# MANIFEST_PATH is relative to CMAKE_CURRENT_SOURCE_DIR.
#
# When corrosion supports dependency tracking, we can use corrosion_import_crate() instead of this function. See:
# https://github.com/corrosion-rs/corrosion/issues/206
# https://github.com/corrosion-rs/corrosion/issues/624
set_property(GLOBAL PROPERTY JOB_POOLS "${JOB_POOLS};cargo=1")

function(import_rust_crate)
    cmake_parse_arguments(PARSE_ARGV 0 ARG "PANIC_UNWIND" "MANIFEST_PATH;CRATE_NAME;FFI_OUTPUT_DIR;FFI_HEADER" "FEATURES;FFI_HEADERS")

    if (NOT ARG_FFI_OUTPUT_DIR)
        set(ARG_FFI_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}")
    endif()
    set(ffi_headers ${ARG_FFI_HEADERS})
    if (ARG_FFI_HEADER)
        list(APPEND ffi_headers "${ARG_FFI_HEADER}")
    endif()
    set(ffi_output "")
    foreach(ffi_header IN LISTS ffi_headers)
        list(APPEND ffi_output "${ARG_FFI_OUTPUT_DIR}/${ffi_header}")
    endforeach()

    _rust_crate_common_setup(
        MANIFEST_PATH "${ARG_MANIFEST_PATH}"
        CRATE_NAME ${ARG_CRATE_NAME}
        FFI_OUTPUT_DIR "${ARG_FFI_OUTPUT_DIR}"
    )

    # Rust's release profile normally aborts on panic. Crates that parse untrusted input may opt
    # into unwinding so they can contain dependency panics at their FFI boundary.
    if (ARG_PANIC_UNWIND)
        list(APPEND cargo_env "CARGO_PROFILE_RELEASE_PANIC=unwind")
    endif()

    set(cargo_feature_flags "")
    if (ARG_FEATURES)
        list(JOIN ARG_FEATURES "," cargo_features)
        list(APPEND cargo_feature_flags "--features=${cargo_features}")
    endif()

    if (WIN32)
        set(output_lib "${cargo_output_dir}/${ARG_CRATE_NAME}.lib")
        set(depfile "${cargo_output_dir}/${ARG_CRATE_NAME}.d")
    else()
        set(output_lib "${cargo_output_dir}/lib${ARG_CRATE_NAME}.a")
        set(depfile "${cargo_output_dir}/lib${ARG_CRATE_NAME}.d")
    endif()

    add_custom_command(
        OUTPUT "${output_lib}"
        COMMAND ${CMAKE_COMMAND}
            -DLOG=${cargo_output_dir}/cargo-${ARG_CRATE_NAME}.log
            -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/run_quiet.cmake"
            --
            ${CMAKE_COMMAND} -E env ${cargo_env} CARGO_TERM_PROGRESS_WHEN=never TERM=dumb
            "${RUST_CARGO}"
                rustc
                --lib
                ${cargo_feature_flags}
                ${cargo_common_flags}
        DEPENDS "${manifest_path}"
            "${workspace_dir}/Cargo.lock" "${workspace_dir}/Cargo.toml"
            "${RUST_RUSTC}" "${CMAKE_SOURCE_DIR}/rust-toolchain.toml"
        DEPFILE "${depfile}"
        COMMENT "Building Rust crate ${ARG_CRATE_NAME}"
        JOB_POOL cargo
        COMMAND_EXPAND_LISTS
    )

    if (ffi_output)
        set(sync_ffi_header_commands "")
        foreach(ffi_header IN LISTS ffi_headers)
            list(APPEND sync_ffi_header_commands
                COMMAND
                    ${CMAKE_COMMAND}
                        -DCARGO_BUILD_SCRIPT_DIR=${cargo_output_dir}/build
                        -DCRATE_NAME=${ARG_CRATE_NAME}
                        -DFFI_HEADER=${ffi_header}
                        -DFFI_OUTPUT_DIR=${ARG_FFI_OUTPUT_DIR}
                        -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/sync_rust_ffi_header.cmake"
            )
        endforeach()

        # Keep Cargo's output separate from copy_if_different outputs. If they share an edge, Ninja's restat timestamp
        # may predate files generated by build.rs and listed in the Cargo depfile, causing the crate to be incorrectly
        # considered dirty on the next build.
        add_custom_command(
            OUTPUT ${ffi_output}
            ${sync_ffi_header_commands}
            DEPENDS "${output_lib}"
            COMMAND_EXPAND_LISTS
        )
    endif()

    add_custom_target(${ARG_CRATE_NAME}-build DEPENDS "${output_lib}" ${ffi_output})

    add_library(${ARG_CRATE_NAME} STATIC IMPORTED GLOBAL)
    set_target_properties(${ARG_CRATE_NAME} PROPERTIES
            IMPORTED_LOCATION "${output_lib}"
            INTERFACE_INCLUDE_DIRECTORIES "${ARG_FFI_OUTPUT_DIR}"
    )
    add_dependencies(${ARG_CRATE_NAME} ${ARG_CRATE_NAME}-build)

    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RustPanicInit.cpp.in"
        "${CMAKE_CURRENT_BINARY_DIR}/${ARG_CRATE_NAME}_panic_init.cpp" @ONLY)
    target_sources(${ARG_CRATE_NAME} INTERFACE
        "${CMAKE_CURRENT_BINARY_DIR}/${ARG_CRATE_NAME}_panic_init.cpp")

    # Rust allocations go through AK so allocator overrides also apply across the FFI boundary.
    target_link_libraries(${ARG_CRATE_NAME} INTERFACE AK)

    # Rust staticlibs bundle the standard library, which on Windows depends on system libraries.
    if (WIN32)
        target_link_libraries(${ARG_CRATE_NAME} INTERFACE kernel32 ntdll Ws2_32 userenv)
    endif()
endfunction()

# build_rust_binary(MANIFEST_PATH path/to/Cargo.toml CRATE_NAME name BINARY_NAME name OUTPUT_PATH_VAR var)
#
# Builds a Rust binary crate target using cargo and exposes the copied binary path through OUTPUT_PATH_VAR.
function(build_rust_binary)
    cmake_parse_arguments(PARSE_ARGV 0 ARG "" "MANIFEST_PATH;CRATE_NAME;BINARY_NAME;OUTPUT_NAME;OUTPUT_PATH_VAR;FFI_OUTPUT_DIR" "FEATURES")

    if (NOT ARG_OUTPUT_NAME)
        set(ARG_OUTPUT_NAME "${ARG_BINARY_NAME}")
    endif()

    _rust_crate_common_setup(
        MANIFEST_PATH "${ARG_MANIFEST_PATH}"
        CRATE_NAME ${ARG_CRATE_NAME}
        FFI_OUTPUT_DIR "${ARG_FFI_OUTPUT_DIR}"
        TARGET_DIR "${CMAKE_BINARY_DIR}/cargo/binaries/${ARG_BINARY_NAME}"
    )

    set(cargo_feature_flags "")
    if (ARG_FEATURES)
        list(JOIN ARG_FEATURES "," cargo_features)
        list(APPEND cargo_feature_flags "--features=${cargo_features}")
    endif()

    set(cargo_binary "${cargo_output_dir}/${ARG_BINARY_NAME}${CMAKE_EXECUTABLE_SUFFIX}")
    set(depfile "${cargo_output_dir}/${ARG_BINARY_NAME}.d")
    set(output_binary "${CMAKE_BINARY_DIR}/bin/${ARG_OUTPUT_NAME}${CMAKE_EXECUTABLE_SUFFIX}")

    add_custom_command(
        OUTPUT "${cargo_binary}"
        COMMAND ${CMAKE_COMMAND}
            -DLOG=${cargo_output_dir}/cargo-${ARG_CRATE_NAME}.log
            -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/run_quiet.cmake"
            --
            ${CMAKE_COMMAND} -E env ${cargo_env} CARGO_TERM_PROGRESS_WHEN=never TERM=dumb
            "${RUST_CARGO}"
                rustc
                --bin ${ARG_BINARY_NAME}
                ${cargo_feature_flags}
                ${cargo_common_flags}
        DEPENDS "${manifest_path}"
            "${workspace_dir}/Cargo.lock" "${workspace_dir}/Cargo.toml"
            "${RUST_RUSTC}" "${CMAKE_SOURCE_DIR}/rust-toolchain.toml"
        DEPFILE "${depfile}"
        COMMENT "Building Rust binary ${ARG_BINARY_NAME}"
        JOB_POOL cargo
        COMMAND_EXPAND_LISTS
    )

    # See the corresponding comment in import_rust_crate(). In addition to avoiding misleading restat timestamps, this
    # lets copy_if_different suppress downstream rebuilds when Cargo recreates an identical binary.
    add_custom_command(
        OUTPUT "${output_binary}"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${cargo_binary}" "${output_binary}"
        DEPENDS "${cargo_binary}"
    )

    add_custom_target(${ARG_BINARY_NAME}-build DEPENDS "${output_binary}")

    if (ARG_OUTPUT_PATH_VAR)
        set(${ARG_OUTPUT_PATH_VAR} "${output_binary}" PARENT_SCOPE)
    endif()
endfunction()

function(test_rust_crate)
    cmake_parse_arguments(PARSE_ARGV 0 ARG "" "MANIFEST_PATH;CRATE_NAME" "")
    _rust_crate_common_setup(
        MANIFEST_PATH "${ARG_MANIFEST_PATH}"
        CRATE_NAME ${ARG_CRATE_NAME}
        TARGET_DIR "${CMAKE_BINARY_DIR}/cargo/tests/${ARG_CRATE_NAME}"
    )
    # cargo test accepts harness arguments after --, not rustc arguments.
    list(FIND cargo_common_flags "--" rustc_flags_start)
    list(SUBLIST cargo_common_flags 0 ${rustc_flags_start} cargo_test_flags)
    # Unit tests exercise internal invariants even when using optimized build artifacts.
    list(APPEND cargo_env "CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS=true")
    add_custom_target(${ARG_CRATE_NAME}-test
        COMMAND ${CMAKE_COMMAND} -E env ${cargo_env}
            "${RUST_CARGO}" test --lib ${cargo_test_flags}
        WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
        USES_TERMINAL
        COMMAND_EXPAND_LISTS
    )
endfunction()

# Shared cargo setup for Rust build and test targets.
function(_rust_crate_common_setup)
    cmake_parse_arguments(PARSE_ARGV 0 ARG "" "MANIFEST_PATH;CRATE_NAME;FFI_OUTPUT_DIR;TARGET_DIR" "")

    set(manifest_path "${CMAKE_CURRENT_SOURCE_DIR}/${ARG_MANIFEST_PATH}")

    # Find the workspace Cargo.lock to track as a dependency.
    get_filename_component(workspace_dir "${manifest_path}" DIRECTORY)
    while(NOT EXISTS "${workspace_dir}/Cargo.lock")
        get_filename_component(workspace_dir "${workspace_dir}" DIRECTORY)
    endwhile()

    # Detect the Rust toolchain.
    find_program(RUST_CARGO cargo REQUIRED)
    find_program(RUST_RUSTC rustc REQUIRED)
    if (NOT DEFINED RUSTC_WRAPPER)
        set(RUSTC_WRAPPER "$ENV{RUSTC_WRAPPER}" CACHE FILEPATH "Path to a rustc wrapper program, e.g. sccache")
    endif()
    if (NOT RUSTC_WRAPPER)
        find_program(SCCACHE_PROGRAM sccache)
        if (SCCACHE_PROGRAM)
            set(RUSTC_WRAPPER "${SCCACHE_PROGRAM}" CACHE FILEPATH "Path to a rustc wrapper program, e.g. sccache" FORCE)
        endif()
    endif()
    if (NOT DEFINED RUST_TARGET_TRIPLE)
        if (ANDROID)
            # Use the Android target triple when cross-compiling to avoid ccache
            # mismatches between host and target architectures.
            if (CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
                set(RUST_TARGET_TRIPLE "aarch64-linux-android" CACHE INTERNAL "Rust target triple")
            elseif (CMAKE_SYSTEM_PROCESSOR STREQUAL "arm")
                set(RUST_TARGET_TRIPLE "armv7-linux-androideabi" CACHE INTERNAL "Rust target triple")
            elseif (CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
                set(RUST_TARGET_TRIPLE "x86_64-linux-android" CACHE INTERNAL "Rust target triple")
            elseif (CMAKE_SYSTEM_PROCESSOR STREQUAL "i686")
                set(RUST_TARGET_TRIPLE "i686-linux-android" CACHE INTERNAL "Rust target triple")
            else()
                message(FATAL_ERROR "Unsupported Android target processor: ${CMAKE_SYSTEM_PROCESSOR}")
            endif()
        else()
            execute_process(COMMAND "${RUST_RUSTC}" -vV OUTPUT_VARIABLE rustc_verbose)
            string(REGEX MATCH "host: ([^\n]+)" _ "${rustc_verbose}")
            string(STRIP "${CMAKE_MATCH_1}" host_triple)
            set(RUST_TARGET_TRIPLE "${host_triple}" CACHE INTERNAL "Rust target triple")
        endif()
    endif()

    # Build the uppercased and underscored variants of the target triple.
    string(REPLACE "-" "_" target_underscore "${RUST_TARGET_TRIPLE}")
    string(TOUPPER "${target_underscore}" target_upper)

    # Determine the cargo profile and output directory name.
    string(TOUPPER "${CMAKE_BUILD_TYPE}" build_type_upper)
    if (build_type_upper STREQUAL "DEBUG")
        set(cargo_profile_flag "")
        set(cargo_profile_dir "debug")
    else()
        set(cargo_profile_flag "--release")
        set(cargo_profile_dir "release")
    endif()

    if (ARG_TARGET_DIR)
        set(cargo_target_dir "${ARG_TARGET_DIR}")
    else()
        set(cargo_target_dir "${CMAKE_BINARY_DIR}/cargo/build")
    endif()
    set(cargo_output_dir "${cargo_target_dir}/${RUST_TARGET_TRIPLE}/${cargo_profile_dir}")

    # Build environment variables for cargo.
    set(cargo_env
        "CC_${target_underscore}=${CMAKE_C_COMPILER}"
        "CXX_${target_underscore}=${CMAKE_CXX_COMPILER}"
        "CARGO_BUILD_RUSTC=${RUST_RUSTC}"
    )

    if (RUSTC_WRAPPER)
        list(APPEND cargo_env
            "RUSTC_WRAPPER=${RUSTC_WRAPPER}"
            "CARGO_INCREMENTAL=0"
        )
    endif()

    if (ARG_FFI_OUTPUT_DIR)
        list(APPEND cargo_env "FFI_OUTPUT_DIR=${ARG_FFI_OUTPUT_DIR}")
    endif()

    # On Windows, rustc invokes the linker directly with MSVC-style flags, so we must not override it with a
    # compiler driver like clang-cl.
    if (NOT WIN32)
        # Resolve the Android NDK sysroot for Rust linking.
        # Prefer ANDROID_NDK_HOME (NDK 26 in CI) over CMAKE_SYSROOT (NDK 29) because
        # NDK 29 removed libunwind.so from sysroot while Rust's aarch64-linux-android
        # target spec still hard-codes -lunwind in the link line. NDK 26's clang driver
        # also auto-injects the correct -L paths at the start of the link command,
        # unlike bare rust-lld which only sees -L paths that precede the -l flag.
        set(rust_ndk_sysroot "")
        set(rust_ndk_home "")
        if (ANDROID)
            if (DEFINED ENV{ANDROID_NDK_HOME} AND EXISTS "$ENV{ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/sysroot")
                set(rust_ndk_home "$ENV{ANDROID_NDK_HOME}")
                set(rust_ndk_sysroot "${rust_ndk_home}/toolchains/llvm/prebuilt/linux-x86_64/sysroot")
            elseif (CMAKE_SYSROOT AND EXISTS "${CMAKE_SYSROOT}")
                set(rust_ndk_sysroot "${CMAKE_SYSROOT}")
            elseif (CMAKE_ANDROID_NDK AND EXISTS "${CMAKE_ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/sysroot")
                set(rust_ndk_home "${CMAKE_ANDROID_NDK}")
                set(rust_ndk_sysroot "${rust_ndk_home}/toolchains/llvm/prebuilt/linux-x86_64/sysroot")
            endif()
        endif()
        if (NOT rust_ndk_sysroot)
            set(rust_ndk_sysroot "/usr/local/lib/android/sdk/ndk/29.0.13599879/toolchains/llvm/prebuilt/linux-x86_64/sysroot")
        endif()

        # Map the Rust target triple to the NDK per-target shared-library directory.
        set(rust_ndk_lib_dir "")
        if (RUST_TARGET_TRIPLE STREQUAL "aarch64-linux-android")
            set(rust_ndk_lib_dir "aarch64-linux-android")
        elseif (RUST_TARGET_TRIPLE STREQUAL "armv7-linux-androideabi")
            set(rust_ndk_lib_dir "arm-linux-androideabi")
        elseif (RUST_TARGET_TRIPLE STREQUAL "x86_64-linux-android")
            set(rust_ndk_lib_dir "x86_64-linux-android")
        elseif (RUST_TARGET_TRIPLE STREQUAL "i686-linux-android")
            set(rust_ndk_lib_dir "x86")
        endif()

        # Choose the Rust linker and build the link arguments.
        #
        # NDK clang driver (preferred when rust_ndk_home is available):
        #   Auto-injects the sysroot -L paths at the start of the link command, so
        #   -llog / -lunwind in the -Bdynamic segment added by Rust's target spec
        #   are resolved correctly. Only -C panic=abort is needed in RUSTFLAGS.
        #
        # Bare rust-lld (fallback):
        #   Does NOT auto-inject -L paths. RUSTFLAGS are always appended AFTER
        #   Rust's target-spec link args, so -L in RUSTFLAGS cannot resolve -llog
        #   in the -Bdynamic segment. This is why we prefer the NDK clang driver.
        #
        # -C panic=abort is MANDATORY on Android: rustc's default dev profile is
        # panic=unwind (LibImageDecoders also opts into unwind via PANIC_UNWIND),
        # which makes rustc add -lunwind to the link line. RUSTFLAGS are appended
        # AFTER cargo's profile -C panic flag, so this overrides any
        # CARGO_PROFILE_*_PANIC=unwind. Desktop (non-Android) is unaffected.
        #
        # NOTE: must stay a single space-joined STRING (not a CMake list).
        # cargo_env elements are expanded as separate argv via COMMAND_EXPAND_LISTS,
        # so any ';' list separator would leak into the RUSTFLAGS value.
        set(rust_linker "rust-lld")
        set(rust_link_args "")
        if (rust_ndk_lib_dir)
            if (rust_ndk_home AND EXISTS "${rust_ndk_home}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang")
                # NDK clang driver: auto-injects sysroot -L paths at command start
                set(rust_linker "${rust_ndk_home}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang")
                set(rust_link_args "-C panic=abort")
            else()
                # Bare rust-lld: -L must precede -l in the command line
                set(rust_link_args "-Clink-arg=-L${rust_ndk_sysroot}/usr/lib/${rust_ndk_lib_dir} -Clink-arg=--sysroot=${rust_ndk_sysroot} -Clink-arg=-llog -C panic=abort")
            endif()

            # Create stub libunwind.so: Android Bionic uses its own unwinder, but
            # Rust's aarch64-linux-android target spec hard-codes -lunwind. NDK does
            # not ship libunwind.so, so build an empty shared library to satisfy it.
            set(stub_lib_dir "${CMAKE_BINARY_DIR}/stub_libs")
            set(stub_unwind_so "${stub_lib_dir}/libunwind.so")
            if (NOT EXISTS "${stub_unwind_so}")
                file(MAKE_DIRECTORY "${stub_lib_dir}")
                file(WRITE "${stub_lib_dir}/unwind_stub.c"
                    "/* Stub: Android Bionic does not use libunwind; this empty library satisfies the linker. */\n")
                execute_process(
                    COMMAND ${CMAKE_C_COMPILER} -shared -fPIC -o "${stub_unwind_so}" "${stub_lib_dir}/unwind_stub.c"
                    RESULT_VARIABLE _stub_result
                    ERROR_VARIABLE _stub_error
                )
                if (NOT _stub_result EQUAL 0)
                    message(WARNING "Failed to create stub libunwind.so: ${_stub_error}")
                endif()
            endif()
            if (EXISTS "${stub_unwind_so}")
                string(APPEND rust_link_args " -Clink-arg=-L${stub_lib_dir}")
            endif()
        endif()

        list(APPEND cargo_env
            "CARGO_TARGET_${target_upper}_LINKER=${rust_linker}"
            "AR_${target_underscore}=${CMAKE_AR}"
            # Always add stub_libs and sysroot lib path to RUSTFLAGS for Rust linking
            "CARGO_TARGET_${target_upper}_RUSTFLAGS=-Clink-arg=-L${rust_ndk_sysroot}/usr/lib/${rust_ndk_lib_dir} -Clink-arg=--sysroot=${rust_ndk_sysroot} -Clink-arg=-llog ${rust_link_args}"
        )
    endif()

    if (APPLE AND CMAKE_OSX_SYSROOT)
        list(APPEND cargo_env "SDKROOT=${CMAKE_OSX_SYSROOT}")
    endif()

    set(cargo_common_flags
        "--target=${RUST_TARGET_TRIPLE}"
        --package ${ARG_CRATE_NAME}
        --manifest-path "${manifest_path}"
        --target-dir "${cargo_target_dir}"
        ${cargo_profile_flag}
        --
        -Cdefault-linker-libraries=yes
        -D warnings
        --emit=dep-info
    )

    # Populate the variable names used by the public helpers below.
    set(RUST_CARGO "${RUST_CARGO}" PARENT_SCOPE)

    set(cargo_common_flags "${cargo_common_flags}" PARENT_SCOPE)
    set(cargo_env "${cargo_env}" PARENT_SCOPE)
    set(cargo_output_dir "${cargo_output_dir}" PARENT_SCOPE)
    set(manifest_path "${manifest_path}" PARENT_SCOPE)
    set(workspace_dir "${workspace_dir}" PARENT_SCOPE)
endfunction()
